### ISSUE TITLE
Android permissions issues causing app crash

### ISSUE THREAD

**Issue by pagelyadam** [capacitor-community/contacts#22] opened 2021-01-22 06:26 UTC
**Describe the bug**

When request permissions using `Contacts.getPermissions()` the app works on iOS but crashes immediately on Android.

**To Reproduce**
1. Execute following commands: `npx cap copy;npx cap sync;ionic cap sync;ionic cap copy android;npx cap open android`
2. Launched Android Simulator (Pixel 3a API 30 x86)
3. Execute `Contacts.getPermissions()`

At this point, the app crashes though the permissions request dialog does popup.

**Expected behavior**

Request permissions dialog is presented over the running app, `Allow` is clicked, contacts are retreived and the Ionic select picker is presented with the list of contacts.

**Screenshots**

Can provide a video, if it would help.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7
 - Browser: NA
 - Version: MacOS 10.15.7

**Smartphone (please complete the following information):**
 - Device: Android Pixel 3a
 - OS: Android 10+ (API 30)
 - Browser: NA
 - Version: 10+ (API 30)

**Additional context**

I have added the required entries to the AndroidManifest but the app crashes when asking for permissions to contacts. A confirmation dialog would popup asking the user to allow access to the contacts but the app would crash immediately.

```
2021-01-21 23:15:55.285 10056-10486/com.puretrim.app E/Capacitor: Serious error executing plugin
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{93554ff 10056:com.puretrim.app/u0a157} (pid=10056, uid=10157) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5702)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6813)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2930)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
        at android.content.ContentResolver.query(ContentResolver.java:1167)
        at android.content.ContentResolver.query(ContentResolver.java:1115)
        at android.content.ContentResolver.query(ContentResolver.java:1071)
        at ch.byrds.capacitor.contacts.Contacts.getContacts(Contacts.java:99)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7129)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7568)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2381)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2861)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
2021-01-21 23:15:55.290 10056-10056/com.puretrim.app D/Capacitor: App paused
2021-01-21 23:15:55.296 10056-10486/com.puretrim.app E/AndroidRuntime: FATAL EXCEPTION: CapacitorPlugins
    Process: com.puretrim.app, PID: 10056
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.getcapacitor.Bridge$1.run(Bridge.java:551)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{93554ff 10056:com.puretrim.app/u0a157} (pid=10056, uid=10157) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5702)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6813)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2930)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
        at android.content.ContentResolver.query(ContentResolver.java:1167)
        at android.content.ContentResolver.query(ContentResolver.java:1115)
        at android.content.ContentResolver.query(ContentResolver.java:1071)
        at ch.byrds.capacitor.contacts.Contacts.getContacts(Contacts.java:99)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99) 
        at com.getcapacitor.Bridge$1.run(Bridge.java:542) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:7129)
        at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:7568)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2381)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2861)
        at android.os.Binder.execTransactInternal(Binder.java:1154)
2021-01-21 23:15:55.363 10056-10486/com.puretrim.app I/Process: Sending signal. PID: 10056 SIG: 9
```

If I manually give the app Contacts permissions, nothing happens. The app does not crash nor does it actually trigger the API to grab the contacts.

Here is the code:

```
    async doSelectContact() {
      const { Contacts } = Plugins;

      Contacts.getPermissions()

      this.picker.buttons = [
        {
          text: 'Cancel',
          role: 'cancel'
        },
        {
          text: 'Confirm',
          handler: (value) => {
            this.doAddContact(value)
          }
        }
      ]

      if (this.contacts.length <= 0) {
        await Contacts.getContacts().then(async (contacts) => {
          await contacts.contacts.forEach(contact => {
            if (contact.phoneNumbers.length >= 1) {
              this.contacts.push({
                text: contact.displayName,
                value: contact.phoneNumbers[0]
              })
            }

            this.picker.columns = [{
              name: 'Contacts',
              options: this.contacts
            }]

            this.picker.open = true
          })
        });
      }
    },
```

**Comment by Idrimi** [comment] 2021-01-25 23:28
i guess this is related to this one: 
https://github.com/capacitor-community/contacts#android-notes

For Android you have to add the permisions in your AndroidManifest.xml. Add the following permissions before the closing of the "manifest" tag.

<uses-permission android:name="android.permission.READ_CONTACTS" />
<uses-permission android:name="android.permission.WRITE_CONTACTS"/>

**Comment by recoiladam** [comment] 2021-01-25 23:31
> i guess this is related to this one:
> https://github.com/capacitor-community/contacts#android-notes
> 
> For Android you have to add the permisions in your AndroidManifest.xml. Add the following permissions before the closing of the "manifest" tag.
> 
> ```
> <uses-permission android:name="android.permission.READ_CONTACTS" />
> <uses-permission android:name="android.permission.WRITE_CONTACTS"/>
> ```

Thank you but I have already done this and I am still getting errors and having problems. I added these lines to `android/app/src/main/AndroidManifeset.xml`. This is not my first app.

**Comment by Idrimi** [comment] 2021-01-25 23:36
Check this repo, i just updated it. Should work. https://github.com/byrdsandbytes/capContactsDemo/tree/capacitor-community
(make sure to use community branch)

Maybe you can copy paste some code snippets.

**Comment by recoiladam** [comment] 2021-01-25 23:43
> Check this repo, i just updated it. Should work. https://github.com/byrdsandbytes/capContactsDemo/tree/capacitor-community
> (make sure to use community branch)
> 
> Maybe you can copy paste some code snippets.

I am not trying to be rude but did you even see where I said I am using Vue and it works fine on iOS? I appreciate you trying to help and all but it's wasting my time since the code is fine considering the issue is with permissions on Android devices. I have gone through all of the necessary steps as outlined and the problem still occurs.

**Comment by recoiladam** [comment] 2021-01-26 00:59
Okay, I got it working. For those using Vue, getPermissions() has to be a promise. Here's how I got it working:

```
      const { Contacts } = Plugins;

      Contacts.getPermissions().then(async(result) => {
        console.log("Permission", result)

        this.picker.buttons = [
          {
            text: 'Cancel',
            role: 'cancel'
          },
          {
            text: 'Confirm',
            handler: (value) => {
              this.doAddContact(value)
            }
          }
        ]

        if (this.contacts.length <= 0) {
          await Contacts.getContacts().then(async (contacts) => {
            await contacts.contacts.forEach(contact => {
              if (contact.phoneNumbers.length >= 1) {
                this.contacts.push({
                  text: contact.displayName,
                  value: contact.phoneNumbers[0]
                })
              }

              this.picker.columns = [{
                name: 'Contacts',
                options: this.contacts
              }]

              this.picker.open = true
            })
          });
        }
      })
```

This can be closed.

**Comment by Idrimi** [comment] 2021-01-26 12:06
> > Check this repo, i just updated it. Should work. https://github.com/byrdsandbytes/capContactsDemo/tree/capacitor-community
> > (make sure to use community branch)
> > Maybe you can copy paste some code snippets.
> 
> I am not trying to be rude but did you even see where I said it works fine on iOS? Also, I am using Vue. I appreciate your trying to help and all but it's wasting my time since the code is fine considering the issue is with permissions on Android devices. I have gone through all of the necessary steps as outlined and the problem still occurs.

1. You're being rude.
2. You posted your android logs. So, yes. 
3. No, your code isn't fine. You just didn't handle the promise right. Which is documented and even has a code snippet to copy paste here: https://github.com/capacitor-community/contacts#usage--examples . Which is indeed embarrassing, considering the fact you call yourself a veteran.
4. I'm wasting your time? You're using my code and I'm helping you fix a bug in your code, which could be prevented by reading the docs. You Sir, are delusional.

**Closed** 2021-01-27 08:58 UTC

**Comment by bfan1256** [comment] 2021-02-02 18:02
Hi, I may like to reopen this as if the user selects "deny" during the permission scheme, it seems to crash the android application.

**Comment by Idrimi** [comment] 2021-02-02 18:35
Hi @bfan1256,

try to ask make sure that you have the permission before you try to fetch contacts. The Code above from @recoiladam is not awaiting the right answer from getPermission().

The answer will look like this:

```
export interface PermissionStatus {
  granted: boolean;
}
```

So just check if you have "granted" is true. Then fetch contacts.

**Comment by recoiladam** [comment] 2021-02-02 21:46
> Ahh I see, so the `getPermission()` doesn't produce an error if it's denied.
> Would the code below work?
> 
> ```ts
> const res = await Contacts.getPermissions()
> if (res.granted) {
>   const result = await Contacts.getContacts();
>   const phoneContacts = result.contacts
> }
> ```

You need to handle it using the promise. Use this:

```
await Contacts.getPermissions().then((response) => {
  if (response.granted) {
    const result = await Contacts.getContacts();
    const phoneContacts = result.contacts
  }
})
```

**Comment by bfan1256** [comment] 2021-02-02 21:51
Sorry, I forgot to say that my solution does work using `async/await` feature

**Comment by Idrimi** [comment] 2021-02-03 11:23
> > Ahh I see, so the `getPermission()` doesn't produce an error if it's denied.
> > Would the code below work?
> > ```ts
> > const res = await Contacts.getPermissions()
> > if (res.granted) {
> >   const result = await Contacts.getContacts();
> >   const phoneContacts = result.contacts
> > }
> > ```
> 
> You need to handle it using the promise. Use this:
> 
> ```
> await Contacts.getPermissions().then((response) => {
>   if (response.granted) {
>     const result = await Contacts.getContacts();
>     const phoneContacts = result.contacts
>   }
> })
> ```

Exactly. This should work.

**Comment by FrnCo-75** [comment] 2024-06-19 19:53
hello, it is my first app. It works using expo go, but when i build the apk file and install it on my mobile (android) it crashes on start. this is an extract of the log of the errors. In my app there is no logic involving the request of READ_CONTACTS permission so i do not understand where this come from and how to fix it. Thanks!!


06-18 00:20:09.953 18700 18700 E AndroidRuntime: FATAL EXCEPTION: main
06-18 00:20:09.953 18700 18700 E AndroidRuntime: Process: com.android.systemui, PID: 18700
06-18 00:20:09.953 18700 18700 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.android.systemui.SystemUIService: android.view.InflateException: Binary XML file line #54 in com.android.systemui:layout/super_notification_shade: uid=10112 needs permission android.permission.READ_CONTACTS to read lock_screen_owner_info_enabled for user 0
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4204)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #54 in com.android.systemui:layout/super_notification_shade: uid=10112 needs permission android.permission.READ_CONTACTS to read lock_screen_owner_info_enabled for user 0
06-18 00:20:09.953 18700 18700 E AndroidRuntime: Caused by: java.lang.SecurityException: uid=10112 needs permission android.permission.READ_CONTACTS to read lock_screen_owner_info_enabled for user 0
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.widget.ILockSettings$Stub$Proxy.getBoolean(ILockSettings.java:1079)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.widget.LockPatternUtils.getBoolean(LockPatternUtils.java:1213)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.widget.LockPatternUtils.isOwnerInfoEnabled(LockPatternUtils.java:715)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.keyguard.KeyguardStatusView.updateOwnerInfo(KeyguardStatusView.java:304)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.keyguard.KeyguardStatusView.onFinishInflate(KeyguardStatusView.java:204)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1134)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1261)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1117)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.statusbar.SuperStatusBarViewFactory.getNotificationShadeWindowView(SuperStatusBarViewFactory.java:74)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.inflateStatusBarWindow(StatusBar.java:1431)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.makeStatusBarView(StatusBar.java:1000)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:2597)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:863)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:204)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:143)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:66)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4192)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService.checkReadPermission(LockSettingsService.java:1058)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.server.locksettings.LockSettingsService.getBoolean(LockSettingsService.java:1162)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at com.android.internal.widget.ILockSettings$Stub.onTransact(ILockSettings.java:462)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1123)
06-18 00:20:09.953 18700 18700 E AndroidRuntime: 
06-18 00:20:09.953   582  1578 I am_crash: [18700,0,com.android.systemui,818462221,java.lang.SecurityException,Remote stack trace:
06-18 00:20:09.953   582  1578 I am_crash: 	at com.android.server.locksettings.LockSettingsService.checkReadPermission(LockSettingsService.java:1058)
06-18 00:20:09.953   582  1578 I am_crash: 	at com.android.server.locksettings.LockSettingsService.getBoolean(LockSettingsService.java:1162)
06-18 00:20:09.953   582  1578 I am_crash: 	at com.android.internal.widget.ILockSettings$Stub.onTransact(ILockSettings.java:462)
06-18 00:20:09.953   582  1578 I am_crash: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
06-18 00:20:09.953   582  1578 I am_crash: 	at android.os.Binder.execTransact(Binder.java:1123)
06-18 00:20:09.953   582  1578 I am_crash: ,Parcel.java,2373]
06-18 00:20:09.955   582  1578 W ActivityManager: Process com.android.systemui has crashed too many times: killing!
